const MAX_FRAMES_COUNT = 16
const MIN_FRAMES_COUNT = 1
const MAX_FRAME_LINES = 100
const MAX_FRAME_CHARACTERS = 5000
const SNIPPET_NAME_MIN_LENGTH = 3
const SNIPPET_NAME_MAX_LENGTH = 150
const SNIPPET_DESCRIPTION_MIN_LENGTH = 10
const SNIPPET_DESCRIPTION_MAX_LENGTH = 1000

export {
  MAX_FRAMES_COUNT,
  MIN_FRAMES_COUNT,
  MAX_FRAME_LINES,
  MAX_FRAME_CHARACTERS,
  SNIPPET_NAME_MIN_LENGTH,
  SNIPPET_NAME_MAX_LENGTH,
  SNIPPET_DESCRIPTION_MIN_LENGTH,
  SNIPPET_DESCRIPTION_MAX_LENGTH,
}
